BlogBundle\Entity\Tag:
    properties:
        name:
            - NotBlank: {message: "El título no puede estar vacio"}
            - Length:
                min: 2
                minMessage: "El nombre tiene que tener más de dos carácteres"